#Example of yaml-Stack file Resource Below -- Written By Me.
AWSTemplateFormatVersion: 2010-09-09
Description: creating an ec2 instance

Resources:
  olaabEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: olaabKP
      ImageId: ami-020cba7c55df1f615
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: olaab-server
      Monitoring: true
      SecurityGroupIds:
        - sg-0d9834d5b7f2f2d57
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo echo "Hello Trinity Server" > /var/www/html/index.html  
      
Outputs:
  outputolaabEC2Instance:
    Description: output the ec2 instance result
    Value: !Ref olaabEC2Instance